set-option -g default-shell "/usr/bin/zsh" #don't let tmux exit
set-option -g default-command "$SHELL" #don't let tmux exit
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-termite:Tc,xterm-kitty:Tc,alacritty:Tc,xterm-256color:Tc'
set -as terminal-features ",alacritty*:RGB"
#set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features ",xterm-256color:RGB"

# get links work
set -ga terminal-features "*:hyperlinks"

# status bar
set -g status-format[0] '#{W:#I#F }'
#set -g status-bg black
set-option -g status-style bg=default
set -g status-fg colour244

set -g prefix 'M-a'
unbind C-b
bind-key enter new-window
bind-key -n C-. next-window
bind-key -n C-, previous-window
bind-key x kill-pane
bind-key & kill-window
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R
setw -g mode-keys vi
# vi like selection
bind-key -Tcopy-mode-vi v send-keys -X begin-selection

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
