[main]
term=xterm-256color
include=/home/kode/.config/foot/themes/kanagawa_wave 
title=foot
font=ComicShanns Nerd Font:size=16
font-italic=ComicShanns Nerd Font:size=16
font-bold-italic=ComicShanns Nerd Font:size=16
#font=FiraCode Nerd Font:size=16
#font-italic=FiraCode Nerd Font:size=16
#font-bold-italic=FiraCode Nerd Font:size=16

[scrollback]
lines=2000
indicator-format=percentage

[colors]
alpha=1

[key-bindings]
scrollback-up-half-page=Control+Shift+p
scrollback-down-page=Control+Shift+n
search-start=Control+Shift+space
show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+y
spawn-terminal=none

