
[colors.primary]
#background = '#1d1f21' ## default black
#foreground = '#fffbf6'

[font]
#size = 17
size = 11
normal = { family = "ComicShanns Nerd Font", style = "Regular" }
#normal = { family = "Comic code", style = "Regular" }
italic = { style = "Italic" }
bold   = { style = "Bold" }
bold_italic = { style = "Bold Italic" }

[window]
dynamic_title = true
#opacity = 0.9
#blur = true
#title = "READ THE FUCKING MENU!!!"
#title = "RTFM!!!"

[cursor]
style = { shape = "Block" }
#style = { shape = "Bean" }
#vi_mode_style = { shape = "Block" }

[scrolling]
history = 5000

[env]
WINIT_X11_SCALE_FACTOR = "1.66"

[general]
import = ["/home/kode/.config/alacritty/alacritty-theme/themes/kanagawa_wave.toml"]
#import = ["/home/kode/.config/alacritty/alacritty-theme/themes/gruvbox_material_hard_dark.toml"]
#import = ["/home/kode/.config/alacritty/alacritty-theme/themes//enfocado_dark.toml"]
#import = ["/home/kode/.config/alacritty/alacritty-theme/themes/everforest_dark.toml"]
