import = ["/home/kode/.config/alacritty/alacritty-theme/themes/iterm.toml"]

[colors.primary]
background = '#1d1f21' ## default black
#foreground = '#fffbf6'

[font]
size = 9.5  

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_title = false
opacity = 0.8 
title = "RTFM"

[cursor.style]
#shape = "Block"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[env]
WINIT_X11_SCALE_FACTOR = "1.66"
