import = ["/home/kode/.config/alacritty/themes/themes/iterm.toml"]

[font]
size = 16.5

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"
