import = ["/home/kode/.config/alacritty/alacritty-theme/themes/kanagawa_wave.toml"]

[colors.primary]
#background = '#1d1f21' ## default black
#foreground = '#fffbf6'

[font]
size = 9.25
normal = { family = "Terminess Nerd Font", style = "Regular" }
italic = { family = "Terminess Nerd Font", style = "Italic" }
bold   = { family = "Terminess Nerd Font", style = "Bold" }
bold_italic = { family = "Terminess Nerd Font", style = "Bold Italic" }

[window]
dynamic_title = false
opacity = 0.8
title = "RTFM"

[cursor]
style = { shape = "Block" }
#style = { shape = "Bean" }
vi_mode_style = { shape = "Block" }

[scrolling]
history = 5000

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
]

[env]
WINIT_X11_SCALE_FACTOR = "1.66"
